package models.matches.yr2018;

public class SingleScoreBreakdown_PowerUp {
	public int adjustPoints;
	public int autoOwnershipPoints;
	public int autoPoints;
	public boolean autoQuestRankingPoint;
	public String autoRobot1;
	public String autoRobot2;
	public String autoRobot3;
	public int autoRunPoints;
	public int autoScaleOwnershipSec;
	public boolean autoSwitchAtZero;
	public int autoSwitchOwnershipSec;
	public int endgamePoints;
	public String endgameRobot1;
	public String endgameRobot2;
	public String endgameRobot3;
	public boolean faceTheBossRankingPoint;
	public int foulCount;
	public int foulPoints;
	public int rp;
	public int techFoulCount;
	public int teleopOwnershipPoints;
	public int teleopPoints;
	public int teleopScaleBoostSec;
	public int teleopScaleForceSec;
	public int teleopScaleOwnershipSec;
	public int teleopSwitchBoostSec;
	public int teleopSwitchForceSec;
	public int teleopSwitchOwnershipSec;
	public int totalPoints;
	public int vaultBoostPlayed;
	public int vaultBoostTotal;
	public int vaultForcePlayed;
	public int vaultForceTotal;
	public int vaultLevitatePlayed;
	public int vaultLevitateTotal;
	public int vaultPoints;
}
